SPOOL \Users\december\Desktop\assignment2\solution1
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

EXPLAIN PLAN FOR SELECT * FROM ORDER_DETAIL WHERE PRODUCT_NAME = 'BOLT' AND QUANTITY > 100;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

EXPLAIN PLAN FOR SELECT UNIT_PRICE FROM ORDER_DETAIL WHERE QUANTITY IN (100, 200, 300) OR DISCOUNT = 0.01;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX OD_INX_QD ON ORDER_DETAIL(QUANTITY,DISCOUNT,UNIT_PRICE);
EXPLAIN PLAN FOR SELECT UNIT_PRICE FROM ORDER_DETAIL WHERE QUANTITY IN (100, 200, 300) OR DISCOUNT = 0.01;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
DROP INDEX OD_INX_QD;


EXPLAIN PLAN FOR SELECT CATEGORY_NAME, SUPPLIER_NAME, COUNT(*)
FROM PRODUCT
GROUP BY CATEGORY_NAME, SUPPLIER_NAME;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
CREATE INDEX PR_IDX_CS ON PRODUCT(CATEGORY_NAME,SUPPLIER_NAME);
EXPLAIN PLAN FOR SELECT CATEGORY_NAME, SUPPLIER_NAME, COUNT(*)
FROM PRODUCT
GROUP BY CATEGORY_NAME, SUPPLIER_NAME;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
DROP INDEX PR_IDX_CS;



EXPLAIN PLAN FOR SELECT SUPPLIER_NAME, UNIT_PRICE
FROM PRODUCT
ORDER BY UNIT_PRICE, QUANTITY_PER_UNIT;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
CREATE INDEX PR_IDX_UQ ON PRODUCT(UNIT_PRICE, QUANTITY_PER_UNIT,SUPPLIER_NAME);
EXPLAIN PLAN FOR SELECT SUPPLIER_NAME, UNIT_PRICE
FROM PRODUCT
ORDER BY UNIT_PRICE, QUANTITY_PER_UNIT;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
DROP INDEX PR_IDX_UQ;


EXPLAIN PLAN FOR SELECT SUPPLIER.COMPANY_NAME, SUPPLIER.CITY
FROM PRODUCT JOIN SUPPLIER
ON PRODUCT.SUPPLIER_NAME = SUPPLIER.COMPANY_NAME;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
CREATE INDEX PR_IDX_SN ON PRODUCT(SUPPLIER_NAME);
CREATE INDEX SP_IDX_CN ON SUPPLIER(COMPANY_NAME,CITY);
EXPLAIN PLAN FOR SELECT SUPPLIER.COMPANY_NAME, SUPPLIER.CITY
FROM PRODUCT JOIN SUPPLIER
ON PRODUCT.SUPPLIER_NAME = SUPPLIER.COMPANY_NAME;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
DROP INDEX PR_IDX_SN;
DROP INDEX SP_IDX_CN;



SPOOL OFF